[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
copy_trading = "8NMw7pjvKbBe3bNRmxtKidth4LcZT8249Eo2LxVbRvt9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
clean = "cargo clean"
test = "pnpm run tests"
